# Generated by Django 4.1.5 on 2023-01-29 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chatapp", "0001_initial"),
        ("userapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="userapp.user"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="chatapp.room"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="userapp.user"
            ),
        ),
    ]
