# Generated by Django 4.1.5 on 2023-01-29 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movieapp", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="covers",
                verbose_name="Изображение обложки",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="genre",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Жанр"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=50, verbose_name="Наименование фильма"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="video",
            field=models.FileField(upload_to="videos", verbose_name="Ссылка на фильм"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Год выпуска"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Время создания"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="movieapp.movie",
                verbose_name="Название фильма",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Имя комнаты"),
        ),
        migrations.AlterField(
            model_name="room",
            name="password",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Пароль для комнаты"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Время обновления"),
        ),
    ]
