# Generated by Django 4.1.5 on 2023-02-19 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movieapp", "0003_alter_country_options_alter_genre_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="user_created",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
