# Generated by Django 4.1.5 on 2023-02-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movieapp", "0005_rename_user_created_room_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="has_password",
            field=models.BooleanField(default=False, verbose_name="Требуется пароль"),
        ),
        migrations.AlterField(
            model_name="room",
            name="password",
            field=models.CharField(
                blank=True,
                default=1,
                help_text="Оставьте пустым, если пароль не требуется",
                max_length=128,
                verbose_name="Пароль для комнаты (зашифрованный)",
            ),
            preserve_default=False,
        ),
    ]
