# Generated by Django 4.1.5 on 2023-02-19 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movieapp", "0006_room_has_password_alter_room_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="movie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movieapp.movie",
                verbose_name="Название фильма",
            ),
        ),
    ]
