version: "3.10"

services:
  mp_postgres:
    image: postgres:15
    container_name: mp_postgres
    volumes:
      - ~/.pg/pg_data/mp:/var/lib/postgresql/data
    env_file:
      - .env

  movieparty:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mp_django
    depends_on:
      - mp_postgres
      - redis
    volumes:
      - static_volume:/mp/static
      - media_volume:/mp/media
    env_file:
      - .env
    links:
      - mp_postgres:db_mp
    command: bash -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn -b 0.0.0.0:8000 movieparty.wsgi:application"

  redis:
    image: redis:latest
    container_name: mp_redis
    ports:
      - "6379:6379"
    env_file:
      - .env

  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: mp_nginx
    image: mp_nginx
    volumes:
      - static_volume:/mp/static
      - media_volume:/mp/media
    depends_on:
      - movieparty
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"
    env_file:
      - .env

volumes:
  static_volume:
  media_volume:

